import { NextRequest, NextResponse } from "next/server";
import { writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join } from "path";

// Types
interface BuildingPoint {
  x: number;
  y: number;
}

interface Building {
  id: number;
  points: BuildingPoint[];
  height?: number;
  name?: string;
}

interface Feature {
  id: number;
  type: string;
  label?: string;
  points: BuildingPoint[];
  cornerRadius?: number;
  centerline?: BuildingPoint[];
  width?: number;
}

interface ExportRequest {
  buildings: Building[];
  features?: Feature[];
  lotSize?: { width: number; depth: number };
  style?: "realistic" | "blueprint" | "minimal" | "architectural" | "bw";
  format?: "svg" | "dxf" | "png" | "pdf" | "blend";
  scale?: number;
  includeDimensions?: boolean;
  includeNorthArrow?: boolean;
  includeScaleBar?: boolean;
  includeLabels?: boolean;
}

// ─── DXF Generation ──────────────────────────────────────────────────────────

// DXF layer colors (AutoCAD Color Index)
const DXF_LAYER_COLORS: Record<string, number> = {
  PROPERTY_BOUNDARY: 7, // white/black
  STREETS: 8, // gray
  SIDEWALKS: 9, // light gray
  BUILDINGS: 5, // blue
  PARCELS: 3, // green
  VEGETATION: 92, // dark green
  WATER: 4, // cyan
  PARKING: 8, // gray
  LABELS: 7, // white/black
};

class DxfWriter {
  private handle = 256; // start after reserved handles
  private entities: string[] = [];
  private layers: Map<string, number> = new Map();

  addLayer(name: string, color: number) {
    this.layers.set(name, color);
  }

  private nextHandle(): string {
    return (this.handle++).toString(16).toUpperCase();
  }

  addPolyline(
    layer: string,
    points: BuildingPoint[],
    closed: boolean,
    constantWidth: number = 0
  ) {
    if (points.length < 2) return;

    const h = this.nextHandle();
    let entity = `0\nLWPOLYLINE\n5\n${h}\n100\nAcDbEntity\n8\n${layer}\n`;
    entity += `100\nAcDbPolyline\n90\n${points.length}\n70\n${closed ? 1 : 0}\n`;
    if (constantWidth > 0) {
      entity += `43\n${constantWidth}\n`;
    }
    for (const p of points) {
      entity += `10\n${p.x.toFixed(4)}\n20\n${p.y.toFixed(4)}\n`;
    }
    this.entities.push(entity);
  }

  addText(
    layer: string,
    x: number,
    y: number,
    height: number,
    text: string,
    rotation: number = 0
  ) {
    const h = this.nextHandle();
    let entity = `0\nTEXT\n5\n${h}\n100\nAcDbEntity\n8\n${layer}\n`;
    entity += `100\nAcDbText\n`;
    entity += `10\n${x.toFixed(4)}\n20\n${y.toFixed(4)}\n30\n0\n`;
    entity += `40\n${height.toFixed(4)}\n`;
    entity += `1\n${text}\n`;
    if (rotation !== 0) {
      entity += `50\n${rotation.toFixed(2)}\n`;
    }
    entity += `100\nAcDbText\n`;
    this.entities.push(entity);
  }

  addCircle(layer: string, x: number, y: number, radius: number) {
    const h = this.nextHandle();
    let entity = `0\nCIRCLE\n5\n${h}\n100\nAcDbEntity\n8\n${layer}\n`;
    entity += `100\nAcDbCircle\n`;
    entity += `10\n${x.toFixed(4)}\n20\n${y.toFixed(4)}\n30\n0\n`;
    entity += `40\n${radius.toFixed(4)}\n`;
    this.entities.push(entity);
  }

  toString(): string {
    // HEADER section
    let dxf = `999\nDXF generated by HYLO-SP\n`;
    dxf += `0\nSECTION\n2\nHEADER\n`;
    dxf += `9\n$ACADVER\n1\nAC1015\n`; // AutoCAD 2000 format
    dxf += `9\n$INSUNITS\n70\n6\n`; // meters
    dxf += `0\nENDSEC\n`;

    // TABLES section - layer definitions
    dxf += `0\nSECTION\n2\nTABLES\n`;

    // Linetype table
    dxf += `0\nTABLE\n2\nLTYPE\n5\n5\n100\nAcDbSymbolTable\n70\n1\n`;
    dxf += `0\nLTYPE\n5\n14\n100\nAcDbSymbolTableRecord\n100\nAcDbLinetypeTableRecord\n`;
    dxf += `2\nCONTINUOUS\n70\n0\n3\nSolid line\n72\n65\n73\n0\n40\n0.0\n`;
    dxf += `0\nENDTAB\n`;

    // Layer table
    dxf += `0\nTABLE\n2\nLAYER\n5\n2\n100\nAcDbSymbolTable\n70\n${this.layers.size}\n`;
    for (const [name, color] of this.layers) {
      const h = this.nextHandle();
      dxf += `0\nLAYER\n5\n${h}\n100\nAcDbSymbolTableRecord\n100\nAcDbLayerTableRecord\n`;
      dxf += `2\n${name}\n70\n0\n62\n${color}\n6\nCONTINUOUS\n`;
    }
    dxf += `0\nENDTAB\n`;

    dxf += `0\nENDSEC\n`;

    // ENTITIES section
    dxf += `0\nSECTION\n2\nENTITIES\n`;
    dxf += this.entities.join("");
    dxf += `0\nENDSEC\n`;

    // EOF
    dxf += `0\nEOF\n`;

    return dxf;
  }
}

function generateDxf(
  buildings: Building[],
  features: Feature[],
  lotSize: { width: number; depth: number },
  includeLabels: boolean
): string {
  const dxf = new DxfWriter();
  const scaleX = lotSize.width / 100;
  const scaleY = lotSize.depth / 100;

  // Helper to convert coordinates: normalize 0-100 → real-world meters, flip Y
  const toReal = (p: BuildingPoint) => ({
    x: p.x * scaleX,
    y: (100 - p.y) * scaleY, // flip Y for CAD (Y-up)
  });

  // Register all layers
  for (const [name, color] of Object.entries(DXF_LAYER_COLORS)) {
    dxf.addLayer(name, color);
  }

  // Property boundary
  const boundary = [
    { x: 0, y: 0 },
    { x: lotSize.width, y: 0 },
    { x: lotSize.width, y: lotSize.depth },
    { x: 0, y: lotSize.depth },
  ];
  dxf.addPolyline("PROPERTY_BOUNDARY", boundary, true);

  // Export features by type
  const featuresByType = new Map<string, Feature[]>();
  for (const f of features) {
    const list = featuresByType.get(f.type) || [];
    list.push(f);
    featuresByType.set(f.type, list);
  }

  // Streets - use centerlines with width when available
  const streets = featuresByType.get("street") || [];
  for (const street of streets) {
    const layerName = "STREETS";
    if (street.centerline && street.centerline.length >= 2) {
      // Centerline as polyline with width
      const realCenterline = street.centerline.map(toReal);
      const realWidth = (street.width || 5) * scaleX;
      dxf.addPolyline(layerName, realCenterline, false, realWidth);
    } else if (street.points.length >= 3) {
      // Fallback: polygon outline
      const realPoints = street.points.map(toReal);
      dxf.addPolyline(layerName, realPoints, true);
    }

    if (includeLabels && street.label && street.centerline) {
      const mid =
        street.centerline[Math.floor(street.centerline.length / 2)];
      const realMid = toReal(mid);
      // Calculate text rotation from centerline direction
      const i = Math.floor(street.centerline.length / 2);
      const prev = street.centerline[Math.max(0, i - 1)];
      const next =
        street.centerline[Math.min(street.centerline.length - 1, i + 1)];
      const angle =
        (Math.atan2(
          (100 - next.y) * scaleY - (100 - prev.y) * scaleY,
          next.x * scaleX - prev.x * scaleX
        ) *
          180) /
        Math.PI;
      dxf.addText(
        "LABELS",
        realMid.x,
        realMid.y,
        (street.width || 5) * scaleX * 0.3,
        street.label,
        angle
      );
    }
  }

  // Sidewalks
  for (const f of featuresByType.get("sidewalk") || []) {
    if (f.points.length >= 3) {
      dxf.addPolyline("SIDEWALKS", f.points.map(toReal), true);
    }
  }

  // Parcels
  for (const f of featuresByType.get("parcel") || []) {
    if (f.points.length >= 3) {
      dxf.addPolyline("PARCELS", f.points.map(toReal), true);
    }
  }

  // Vegetation
  for (const f of featuresByType.get("vegetation") || []) {
    if (f.points.length >= 3) {
      dxf.addPolyline("VEGETATION", f.points.map(toReal), true);
      if (includeLabels && f.label) {
        const cx =
          f.points.reduce((s, p) => s + p.x, 0) / f.points.length;
        const cy =
          f.points.reduce((s, p) => s + p.y, 0) / f.points.length;
        const rc = toReal({ x: cx, y: cy });
        dxf.addText("LABELS", rc.x, rc.y, 1.5 * scaleX, f.label);
      }
    }
  }

  // Water
  for (const f of featuresByType.get("water") || []) {
    if (f.points.length >= 3) {
      dxf.addPolyline("WATER", f.points.map(toReal), true);
      if (includeLabels && f.label) {
        const cx =
          f.points.reduce((s, p) => s + p.x, 0) / f.points.length;
        const cy =
          f.points.reduce((s, p) => s + p.y, 0) / f.points.length;
        const rc = toReal({ x: cx, y: cy });
        dxf.addText("LABELS", rc.x, rc.y, 1.5 * scaleX, f.label);
      }
    }
  }

  // Parking
  for (const f of featuresByType.get("parking") || []) {
    if (f.points.length >= 3) {
      dxf.addPolyline("PARKING", f.points.map(toReal), true);
    }
  }

  // Buildings - from features first, fall back to buildings array
  const buildingFeatures = featuresByType.get("building") || [];
  if (buildingFeatures.length > 0) {
    for (const f of buildingFeatures) {
      if (f.points.length >= 3) {
        dxf.addPolyline("BUILDINGS", f.points.map(toReal), true);
        if (includeLabels && f.label) {
          const cx =
            f.points.reduce((s, p) => s + p.x, 0) / f.points.length;
          const cy =
            f.points.reduce((s, p) => s + p.y, 0) / f.points.length;
          const rc = toReal({ x: cx, y: cy });
          dxf.addText("LABELS", rc.x, rc.y, 2 * scaleX, f.label);
        }
      }
    }
  } else {
    // Fallback to buildings array
    for (const b of buildings) {
      if (b.points.length >= 3) {
        dxf.addPolyline("BUILDINGS", b.points.map(toReal), true);
        if (includeLabels && b.name) {
          const cx =
            b.points.reduce((s, p) => s + p.x, 0) / b.points.length;
          const cy =
            b.points.reduce((s, p) => s + p.y, 0) / b.points.length;
          const rc = toReal({ x: cx, y: cy });
          dxf.addText("LABELS", rc.x, rc.y, 2 * scaleX, b.name);
        }
      }
    }
  }

  // North arrow indicator (circle + text at top-right)
  dxf.addCircle(
    "PROPERTY_BOUNDARY",
    lotSize.width * 0.92,
    lotSize.depth * 0.92,
    lotSize.width * 0.02
  );
  dxf.addText(
    "LABELS",
    lotSize.width * 0.92,
    lotSize.depth * 0.95,
    2 * scaleX,
    "N"
  );

  return dxf.toString();
}

// ─── Styled SVG generation ──────────────────────────────────────────────────

function generateStyledSvg(
  buildings: Building[],
  lotSize: { width: number; depth: number },
  style: string,
  options: {
    includeDimensions: boolean;
    includeNorthArrow: boolean;
    includeScaleBar: boolean;
    includeLabels: boolean;
    scale: number;
  }
): string {
  const viewBox = "0 0 100 100";

  const styles: Record<
    string,
    {
      bg: string;
      stroke: string;
      fill: string;
      text: string;
      grid: string;
    }
  > = {
    blueprint: {
      bg: "#1a3a5c",
      stroke: "#4a90d9",
      fill: "rgba(74, 144, 217, 0.2)",
      text: "#8ec8f0",
      grid: "rgba(74, 144, 217, 0.15)",
    },
    bw: {
      bg: "#ffffff",
      stroke: "#000000",
      fill: "rgba(0, 0, 0, 0.1)",
      text: "#000000",
      grid: "rgba(0, 0, 0, 0.1)",
    },
    architectural: {
      bg: "#f5f5f0",
      stroke: "#2d2d2d",
      fill: "rgba(45, 45, 45, 0.15)",
      text: "#2d2d2d",
      grid: "rgba(45, 45, 45, 0.08)",
    },
    minimal: {
      bg: "#fafafa",
      stroke: "#333333",
      fill: "transparent",
      text: "#666666",
      grid: "rgba(0, 0, 0, 0.05)",
    },
    realistic: {
      bg: "#f0f0e8",
      stroke: "#4a5568",
      fill: "rgba(74, 85, 104, 0.2)",
      text: "#2d3748",
      grid: "rgba(0, 0, 0, 0.06)",
    },
  };

  const s = styles[style] || styles.realistic;

  const paths = buildings
    .map((building, idx) => {
      const points = building.points.map((p) => `${p.x},${p.y}`).join(" ");
      const buildingName = building.name || `B${idx + 1}`;

      let content = `<polygon points="${points}" fill="${s.fill}" stroke="${s.stroke}" stroke-width="0.5"/>`;

      if (options.includeLabels) {
        const centroid = building.points.reduce(
          (acc, p) => ({
            x: acc.x + p.x / building.points.length,
            y: acc.y + p.y / building.points.length,
          }),
          { x: 0, y: 0 }
        );
        content += `<text x="${centroid.x}" y="${centroid.y}" font-size="3" fill="${s.text}" text-anchor="middle" dominant-baseline="middle">${buildingName}</text>`;
      }

      if (options.includeDimensions && building.points.length >= 2) {
        const p1 = building.points[0];
        const p2 = building.points[1];
        const width = Math.sqrt(
          Math.pow(p2.x - p1.x, 2) + Math.pow(p2.y - p1.y, 2)
        );
        const realWidth = ((width / 100) * lotSize.width).toFixed(1);

        content += `<line x1="${p1.x}" y1="${p1.y - 3}" x2="${p2.x}" y2="${p2.y - 3}" stroke="${s.text}" stroke-width="0.2" stroke-dasharray="1,0.5"/>`;
        content += `<text x="${(p1.x + p2.x) / 2}" y="${(p1.y + p2.y) / 2 - 4}" font-size="2" fill="${s.text}" text-anchor="middle">${realWidth}m</text>`;
      }

      return content;
    })
    .join("\n");

  const northArrow = options.includeNorthArrow
    ? `<g transform="translate(90, 10)">
      <polygon points="0,-8 3,0 -3,0" fill="${s.stroke}"/>
      <text x="0" y="-10" font-size="3" fill="${s.text}" text-anchor="middle">N</text>
    </g>`
    : "";

  const scaleBar = options.includeScaleBar
    ? `<g transform="translate(10, 93)">
      <line x1="0" y1="0" x2="10" y2="0" stroke="${s.stroke}" stroke-width="0.5"/>
      <line x1="0" y1="-2" x2="0" y2="2" stroke="${s.stroke}" stroke-width="0.5"/>
      <line x1="10" y1="-2" x2="10" y2="2" stroke="${s.stroke}" stroke-width="0.5"/>
      <text x="5" y="4" font-size="2" fill="${s.text}" text-anchor="middle">${((10 / 100) * lotSize.width).toFixed(0)}m</text>
    </g>`
    : "";

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" style="background-color: ${s.bg}; width: 100%; height: 100%;">
  <defs>
    <pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse">
      <path d="M 10 0 L 0 0 0 10" fill="none" stroke="${s.grid}" stroke-width="0.2"/>
    </pattern>
  </defs>
  <rect width="100" height="100" fill="url(#grid)"/>
  <rect x="5" y="5" width="90" height="90" fill="none" stroke="${s.stroke}" stroke-width="0.5" stroke-dasharray="2,1"/>
  ${paths}
  ${northArrow}
  ${scaleBar}
  <text x="5" y="97" font-size="2.5" fill="${s.text}">Generated by HYLO-SP</text>
</svg>`;
}

// ─── PNG generation using Sharp ─────────────────────────────────────────────

async function generatePng(svgContent: string): Promise<Buffer> {
  try {
    const sharp = (await import("sharp")).default;
    return await sharp(Buffer.from(svgContent))
      .resize(2000, 2000, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 1 } })
      .png()
      .toBuffer();
  } catch {
    // If sharp fails, return the SVG as-is (browser can handle it)
    throw new Error("PNG generation requires sharp. Install with: npm install sharp");
  }
}

// ─── Route handler ──────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    const body: ExportRequest = await request.json();
    const {
      buildings,
      features = [],
      lotSize = { width: 100, depth: 100 },
      style = "realistic",
      format = "svg",
      includeDimensions = true,
      includeNorthArrow = true,
      includeScaleBar = true,
      includeLabels = true,
      scale = 50,
    } = body;

    if (
      (!buildings || buildings.length === 0) &&
      (!features || features.length === 0)
    ) {
      return NextResponse.json(
        { error: "Buildings or features array is required" },
        { status: 400 }
      );
    }

    let output: string | Buffer;
    let contentType: string;
    let filename: string;
    let isBinary = false;

    switch (format) {
      case "svg":
        output = generateStyledSvg(buildings, lotSize, style, {
          includeDimensions,
          includeNorthArrow,
          includeScaleBar,
          includeLabels,
          scale,
        });
        contentType = "image/svg+xml";
        filename = `site-plan-${style}.svg`;
        break;

      case "dxf":
        output = generateDxf(buildings, features, lotSize, includeLabels);
        contentType = "application/dxf";
        filename = `site-plan.dxf`;
        break;

      case "pdf":
        output = generateStyledSvg(buildings, lotSize, style, {
          includeDimensions,
          includeNorthArrow,
          includeScaleBar,
          includeLabels,
          scale,
        });
        contentType = "image/svg+xml";
        filename = `site-plan-${style}.svg`;
        break;

      case "png": {
        const svgForPng = generateStyledSvg(buildings, lotSize, style, {
          includeDimensions,
          includeNorthArrow,
          includeScaleBar,
          includeLabels,
          scale,
        });
        try {
          output = await generatePng(svgForPng);
          contentType = "image/png";
          filename = `site-plan-${style}.png`;
          isBinary = true;
        } catch {
          // Fallback to SVG if PNG generation fails
          output = svgForPng;
          contentType = "image/svg+xml";
          filename = `site-plan-${style}.svg`;
        }
        break;
      }

      case "blend":
        output = `# HYLO-SP Blender Export\n# Buildings: ${buildings.length}\n# Style: ${style}\n# Lot Size: ${lotSize.width}m x ${lotSize.depth}m\n\nimport bpy\n\nbpy.ops.object.select_all(action='SELECT')\nbpy.ops.object.delete()\n\nbpy.ops.mesh.primitive_plane_add(size=${Math.max(lotSize.width, lotSize.depth)})\nground = bpy.context.object\nground.name = "Ground"\n\n${buildings
          .map(
            (b, i) =>
              `bpy.ops.mesh.primitive_cube_add(size=1, location=(${b.points[0]?.x || 0}, ${b.points[0]?.y || 0}, 1.5))\nbuilding = bpy.context.object\nbuilding.name = "${b.name || `Building_${i + 1}`}"\nbuilding.scale = (${b.points[1]?.x ? (b.points[1].x - b.points[0].x) * lotSize.width / 100 : 5}, ${b.points[1]?.y ? (b.points[1].y - b.points[0].y) * lotSize.depth / 100 : 5}, 3)`
          )
          .join("\n\n")}\n\nprint("Scene created from HYLO-SP export")`;
        contentType = "text/x-python";
        filename = `site-plan.blend.py`;
        break;

      default:
        return NextResponse.json(
          { error: `Unsupported format: ${format}` },
          { status: 400 }
        );
    }

    // Save to file
    const exportsDir = join(process.cwd(), "exports");
    if (!existsSync(exportsDir)) {
      await mkdir(exportsDir, { recursive: true });
    }

    const timestamp = Date.now();
    const filePath = join(exportsDir, `${timestamp}-${filename}`);
    await writeFile(filePath, output);

    // For binary formats, base64 encode the content
    const responseContent = isBinary
      ? `data:${contentType};base64,${(output as Buffer).toString("base64")}`
      : (output as string);

    return NextResponse.json({
      success: true,
      filename,
      content: responseContent,
      contentType,
      downloadUrl: `/exports/${timestamp}-${filename}`,
      data: {
        format,
        style,
        buildingCount: buildings.length,
        featureCount: features.length,
        lotSize,
      },
    });
  } catch (error) {
    console.error("Error generating export:", error);
    return NextResponse.json(
      { error: "Failed to generate export" },
      { status: 500 }
    );
  }
}
